dist: trusty
sudo: required

language: node_js
node_js:
  - "stable"

addons:
  sonarcloud:
    organization: "praneshkumarthangavel-github"
    token:
      secure: "405a2c239b66a9b89ffc423bf1a09b136bed732e"
  sauce_connect:
    username: "praneshkumarthangavel"
    access_key: "5470f408-2d3f-47bc-a259-56732c2ea89f"
    
script:
  - sonar-scanner
  - npm test