dist: trusty
sudo: required

language: node_js
node_js:
  - "stable"

addons:
  sonarcloud:
    organization: "praneshkumarthangavel-github"
    token:
      secure: "405a2c239b66a9b89ffc423bf1a09b136bed732e"
#   sauce_connect:
#     username: "kishanlalbj"
#     access_key: "670e4c84-0b38-48b8-b49b-15c7b088bbdc"
    
script:
  - sonar-scanner
  - npm test